### ISSUE TITLE
Tab bars cover first line of terminal

### ISSUE THREAD

**Issue by Phlosioneer** [leo/hyper-native#5]
I have a fresh installation of hyper on windows. I have installed hyper-native through npm, and then put it in the hyper config file under "plugins". It's fully functional, except the top bar is missing, the top line of text is underneath the main menu button, and while active, the tabs cover the top line of text.

If I scroll over the upper-right corner, I do get a red "x". I would guess that the top bar isn't being rendered?

This is what it looks like after typing `cls` followed by `echo "this is the first line"`:
![hyper_native_screenshot](https://user-images.githubusercontent.com/4657718/27051229-54e4209a-4f83-11e7-8adc-f348d69baf93.png)

**Comment by leo** [comment]
This theme is only meant to be used on macOS. Looks like you're using it on Windows... 😊
